apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sds-git-secret
  namespace: argocd
spec:
  encryptedData:
    privateSshKey: bitnami_sealed_secret
    sshPrivateKey: bitnami_sealed_secret
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sds-git-secret
      namespace: argocd
---