apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: git@github.com:cbanciu667/sds-argocd.git
      sshPrivateKeySecret:
        name: sds-git-secret
        key: privateSshKey