apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-docker-credentials
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: bitnami_sealed_secret
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-docker-credentials
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
---
